# Generated by Django 5.1.2 on 2024-10-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('1', 'Health'), ('2', 'Food'), ('3', 'Transportation'), ('4', 'Housing'), ('5', 'Utilities'), ('6', 'Entertainment'), ('7', 'Clothing'), ('8', 'Education'), ('9', 'Travel'), ('10', 'Personal Care'), ('11', 'Gifts'), ('12', 'Insurance'), ('13', 'Investments'), ('14', 'Lend money'), ('15', 'Other')], max_length=2)),
                ('type', models.CharField(choices=[('1', 'Expense'), ('2', 'Income')], max_length=2)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('1', 'Cash'), ('2', 'Credit Card'), ('3', 'Debit Card'), ('4', 'Bank Transfer'), ('5', 'Check')], max_length=2)),
                ('details', models.TextField(blank=True, null=True)),
                ('account', models.CharField(choices=[('1', 'Checking Account'), ('2', 'Savings Account'), ('3', 'Credit Account'), ('4', 'Cash on Hand')], max_length=2)),
            ],
        ),
    ]
