# Generated by Django 5.1.2 on 2024-10-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[(1, 'Expense'), (2, 'Income')], max_length=2),
        ),
    ]
