# Generated by Django 5.1.2 on 2025-04-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_recurringtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='expense',
        ),
    ]
