# Generated by Django 5.1.2 on 2025-04-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_remove_recurringtransaction_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_date',
            field=models.DateField(),
        ),
    ]
