# Generated by Django 5.1.2 on 2025-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_expense_created_at_expense_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings', models.PositiveIntegerField(default=0)),
                ('fortnightly_budget', models.PositiveIntegerField(default=7500)),
            ],
        ),
    ]
