# Generated by Django 5.1.2 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0016_alter_expense_client_id_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(),
        ),
    ]
